export const designOptionSectionObj = {
  optionCardTitle: 'Designs',
  firstCardImg: 'https://images.pexels.com/photos/1571452/pexels-photo-1571452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  firstCardAlt: 'photo',
  firstCardTitle: 'Modern Designs',
  firstCardLink: '#',
  secondCardImg: 'https://images.pexels.com/photos/1571452/pexels-photo-1571452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  secondCardAlt: 'photo',
  secondCardTitle: 'Antiques',
  secondCardLink: '#',
  thirdCardImg: 'https://images.pexels.com/photos/1571452/pexels-photo-1571452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  thirdCardAlt: 'photo',
  thirdCardTitle: 'Retro Designs',
  thirdCardLink: '#',
  fourthCardImg: 'https://images.pexels.com/photos/1571452/pexels-photo-1571452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  fourthCardAlt: 'photo',
  fourthCardTitle: 'Coastal Designs',
  fourthCardLink: '#',
  fifthCardImg: 'https://images.pexels.com/photos/1571452/pexels-photo-1571452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  fifthCardAlt: 'photo',
  fifthCardTitle: 'Minimalist Designs',
  fifthCardLink: '#',
  sixthCardImg: 'https://images.pexels.com/photos/1571452/pexels-photo-1571452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  sixthCardAlt: 'photo',
  sixthCardTitle: 'Traditional',
  sixthCardLink: '#'
}